# 向量存储配置（PGVector）
collection_name: rag_collection
k: 5
data_path: src/data/knowledge_base
md5_hex_store: src/data/md5_hex_store/md5_hex_store.txt
allow_knowledge_file_types:
  - txt
  - pdf
  - md
  - pptx
  - docx
chunk_size: 200
chunk_overlap: 20
separators:
  - "\n\n"
  - "\n"
  - "。"
  - "！"
  - "？"
  - "!"
  - "?"
  - " "
  - ""